# Generated by Django 4.2.2 on 2024-05-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldatopicmodelling',
            name='lda_list',
        ),
    ]
