# Generated by Django 4.2.2 on 2024-05-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_remove_ldatopicmodelling_lda_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldatopicmodelling',
            name='coherence_value',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ldatopicmodelling',
            name='selected_topics',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
