# Generated by Django 4.2.2 on 2024-05-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0004_lsatopicmodelling'),
    ]

    operations = [
        migrations.AddField(
            model_name='textprocessing',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('pending', 'Pending')], default='ready', max_length=8),
        ),
    ]
