# Generated by Django 4.2.2 on 2024-05-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0006_ldatopicmodelling_results_lsatopicmodelling_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textprocessing',
            name='corpus_path',
            field=models.FileField(max_length=255, upload_to='processed_files/corpora/'),
        ),
        migrations.AlterField(
            model_name='textprocessing',
            name='dictionary_path',
            field=models.FileField(max_length=255, upload_to='processed_files/dictionaries/'),
        ),
        migrations.AlterField(
            model_name='textprocessing',
            name='processed_text_path',
            field=models.FileField(max_length=255, upload_to='processed_files/texts/'),
        ),
    ]
